# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20171003_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_seats',
            field=models.ManyToManyField(related_name='_bus_bus_seats_+', to='reservations.Seat'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='blood_group',
            field=models.CharField(choices=[('o+', 'O+'), ('A+', 'A+')], max_length=50),
        ),
    ]
