# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20171013_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=100, verbose_name='Car Type')),
                ('seat_chart', models.CharField(max_length=100, verbose_name='Seat Chart')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_chart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.SeatChart'),
        ),
    ]
