# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20180504_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
